# Generated by Django 4.1.7 on 2023-04-04 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Топливный', 'Топливный'), ('Машиностроение', 'Машиностроение'), ('ЯОК', 'ЯОК'), ('Энергетический', 'Энергетический')], max_length=20, verbose_name='Название дивизиона')),
            ],
            options={
                'verbose_name': 'Дивизион',
                'verbose_name_plural': 'Дивизионы',
            },
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Название предприятия')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_question.division', verbose_name='Название дивизиона')),
            ],
            options={
                'verbose_name': 'Предприятие',
                'verbose_name_plural': 'Предприятия',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('enterprise', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app_question.enterprise', verbose_name='Предприятие')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
    ]
